chore:
  - head-branch: ['^chore[/|-].*']

bugfix:
  - head-branch: ['^fix[/|-].*', '^bugfix[/|-].*']

feature:
  - head-branch: ['^feature[/|-].*', '^feat[/|-].*']

enhancement:
  - head-branch: ['^refactor[/|-].*']

documentation:
  - head-branch: ['^docs[/|-].*']
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CONTRIBUTING.md
          - LICENSE
          - docs/**/*

has-tests:
  - changed-files:
      - any-glob-to-any-file: tests/**/*

translations:
  - changed-files:
      - any-glob-to-any-file: custom_components/openevse/translations/**/*

dependencies:
  - head-branch: ['^deps[/|-].*', '^dependabot/.*']
