name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
autolabeler:
  - label: "chore"
    branch:
      - "chore-*"
      - "docs-*"
    title:
      - "/^chore(\\s*\\(.*\\))?:/i"
      - "/^docs(\\s*\\(.*\\))?:/i"
  - label: "documentation"
    branch:
      - "docs-*"
    title:
      - "/^docs(\\s*\\(.*\\))?:/i"
  - label: "bugfix"
    branch:
      - "fix-*"
    title:
      - "/^fix(\\s*\\(.*\\))?:/i"
  - label: "feature"
    branch:
      - "feat-*"
    title:
      - "/^feat(\\s*\\(.*\\))?:/i"
  - label: "enhancement"
    branch:
      - "refactor-*"
    title:
      - "/^refactor(\\s*\\(.*\\))?:/i"
  - label: "code-quality"
    branch:
      - "test-*"
    title:
      - "/^test(s)?(\\s*\\(.*\\))?:/i"
  - label: "dependencies"
    branch:
      - "deps-*"
    title:
      - "/^build\\(deps\\):/i"
      - "/^chore\\(deps\\):/i"
categories:
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
  - title: "⚡ Enhancements ⚡"
    labels:
      - "enhancement"
  - title: "✨ New Features ✨"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧 Maintenance 🔧"
    labels:
      - "chore"
      - "docs"
      - "documentation"
    collapse-after: 3
  - title: "🎓 Code Quality 🎓"
    labels:
      - "code-quality"
  - title: "🔩 Dependency 🔩"
    labels:
      - "dependencies"
    collapse-after: 3

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/openevse/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/openevse/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/openevse/issues)
