name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
autolabeler:
  - label: "chore"
    title:
      - "/chore:/i"
  - label: "bugfix"
    title:
      - "/fix:/i"
  - label: "feature"
    title:
      - "/feat:/i"
  - label: "enhancement"
    title:
      - "/refactor:/i"
  - label: "code-quality"
    title:
      - "/tests:/i"
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancements :zap:"
    labels:
      - "enhancement"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":wrench: Maintenance :wrench:"
    labels:
      - "chore"
  - title: ":mortar_board: Code Quality :mortar_board:"
    labels:
      - "code-quality"
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/openevse/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/openevse/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Wiki](https://github.com/firstof9/openevse/wiki)
  - [Submit bugs/feature requests](https://github.com/firstof9/openevse/issues)
