name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
autolabeler:
  - label: "chore"
    title:
      - "/chore:/i"
  - label: "bugfix"
    title:
      - "/fix:/i"
  - label: "feature"
    title:
      - "/feat:/i"
  - label: "enhancement"
    title:
      - "/refactor:/i"
  - label: "code-quality"
    title:
      - "/tests:/i"
  - label: "dependencies"
    title:
      - "/build(deps):/i"      
categories:
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
  - title: "⚡ Enhancements ⚡"
    labels:
      - "enhancement"
  - title: "✨ New Features ✨"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧 Maintenance 🔧"
    labels:
      - "chore"
  - title: "🎓 Code Quality 🎓"
    labels:
      - "code-quality"
  - title: "🔩 Dependency 🔩"
    labels:
      - "dependencies"

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/openevse/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/openevse/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/openevse/issues)
