"""Openevse tests consts."""

import datetime

FW_DATA = {
    "latest_version": "4.1.7",
    "release_notes": '## What\'s Changed\r\n* add upload_progress event to websocket by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/471\r\n* improvment & fixes of MQTT /override topic by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/485\r\n* add "claims_version" event sent at each claims change. by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/474\r\n* override version +  fixes by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/486\r\n* publish override_version after claim engine has treated it. by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/489\r\n* fix  #496 #492 increased json object size by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/497\r\n* Current Shaper now use "max_current" instead of "charge_current". by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/495\r\n* Bump express from 4.17.1 to 4.17.3 in /tesla_login by @dependabot in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/499\r\n* fix missing shaper_updated in /status by @KipK in https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/501\r\n\r\n\r\n**Full Changelog**: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/compare/4.1.6...4.1.7\r\n\r\n## Updating Firmware\r\n\r\nFirmware can be updated via the web interface. **Be sure to select the correct firmware for your hardware and unzip before uploading .bin**\r\n\r\nToggle \'advanced\' display tab to view the hardware info on the main OpenEVSE tab:\r\n\r\n![screenshot from 2022-11-16 15-46-41](https://user-images.githubusercontent.com/758844/202227648-0fc2a97e-1a71-4315-ba2f-69b09cfc0b0e.png)\r\n\r\n\r\n***\r\n\r\n| Firmware  | MD5 |\r\n| ------------- | ------------- |\r\n| bootloader.bin | 633fdf6c2eaa137d81eb1e037c82c1a5mc |\r\n| openevse_esp32-gateway-e.bin | 824918fab878077b318e828657dd33a6 |\r\n| openevse_esp32-gateway-e.bin | 720b7580d94d5df514dfd4b48132904d |\r\n| openevse_huzzah32.bin | 2890dd53a100d9df29d105d9719c04b8 |\r\n| openevse_wifi_v1.bin | 506aa7c43ebf2c9a1115fbee8112686 |\r\n| partitions.bin | 95ff55176b05845b099191ebc17e3b46 |\r\n\r\n',
    "release_url": "https://github.com/OpenEVSE/ESP32_WiFi_V4.x/releases/tag/4.1.7",
}

GETFW_DATA = ("4.1.7", "openevse_wifi_v1")

CHARGER_DATA = {
    "status": "disabled",
    "state": "Sleeping",
    "charge_time_elapsed": 17832,
    "ambient_temperature": 29.6,
    "ir_temperature": None,
    "rtc_temperature": 29.6,
    "esp_temperature": 32.25,
    "usage_session": 29509.52,
    "usage_total": 7642350,
    "openevse_firmware": "7.1.3",
    "protocol_version": None,
    "charging_voltage": 240,
    "charging_current": 0,
    "service_level": 2,
    "max_amps": 48,
    "min_amps": 6,
    "current_capacity": 48,
    "wifi_firmware": "4.1.7",
    "charging_power": 0,
    "wifi_signal": -66,
    "ammeter_scale_factor": 220,
    "divertmode": "normal",
    "charge_rate": 0,
    "shaper_live_power": 0,
    "shaper_current": 0,
    "shaper_max_power": None,
    "vehicle_soc": None,
    "vehicle_range": None,
    "vehicle_eta": None,
    "ota_update": False,
    "vehicle": False,
    "manual_override": False,
    "divert_active": False,
    "using_ethernet": False,
    "shaper_active": False,
    "max_current_soft": 48,
    "led_brightness": 128,
}
CONFIG_DATA = {
    "name": "openevse",
    "host": "openevse.test.tld",
    "username": "",
    "password": "",
}
CONFIG_DATA_GRID = {
    "name": "openevse",
    "host": "openevse.test.tld",
    "username": "",
    "password": "",
    "grid": "sensor.grid_usage",
    "invert_grid": False,
}
CONFIG_DATA_SOLAR = {
    "name": "openevse",
    "host": "openevse.test.tld",
    "username": "",
    "password": "",
    "solar": "sensor.solar_production",
    "voltage": "sensor.grid_voltage",
    "invert_grid": False,
}
DIAG_CONFIG_DATA = {
    "name": "openevse",
    "host": "openevse.test.tld",
    "username": "testuser",
    "password": "a-super-fake-password",
}
DIAG_DEVICE_RESULTS = {
    "ambient_temperature": 50.3,
    "ammeter_scale_factor": 220,
    "charge_rate": 0,
    "charge_time_elapsed": 246,
    "charging_current": 32.2,
    "charging_power": 7728.0,
    "charging_voltage": 240,
    "current_capacity": 40,
    "current_power": 0,
    "divert_active": False,
    "divertmode": "eco",
    "esp_temperature": 56.0,
    "has_limit": False,
    "ir_temperature": None,
    "led_brightness": 64,
    "manual_override": False,
    "max_amps": 48,
    "max_current": 48,
    "max_current_soft": 28,
    "min_amps": 6,
    "mqtt_connected": True,
    "openevse_firmware": "7.1.3",
    "ota_update": False,
    "override_state": "auto",
    "protocol_version": None,
    "rtc_temperature": 50.3,
    "service_level": 2,
    "shaper_active": True,
    "shaper_available_current": 21,
    "shaper_live_power": 2299,
    "shaper_max_power": 4000,
    "shaper_updated": False,
    "state": "sleeping",
    "status": "sleeping",
    "total_day": None,
    "total_month": None,
    "total_week": None,
    "total_year": None,
    "usage_session": 275.71,
    "usage_total": 64582,
    "using_ethernet": False,
    "vehicle": True,
    "vehicle_eta": datetime.datetime(2026, 1, 9, 17, 0, tzinfo=datetime.timezone.utc),
    "vehicle_range": 468,
    "vehicle_soc": 75,
    "wifi_firmware": "v5.1.2",
    "wifi_signal": -61,
}
