set_override:
  name: Set override
  description: Sets override settings on a charger.
  target:
    device:
      integration: openevse
  fields:
    state:
      name: State
      description: Enable or disable charging.
      required: false
      default: disabled
      example: disabled
      selector:
        select:
          options:
            - "active"
            - "disabled"
    charge_current: 
      name: Charge current
      description: Specify the active charge current in Amps
      required: false
      example: 30
      selector:
        number:
          min: 1
          max: 48
          unit_of_measurement: ampers
          mode: box
    max_current:
      name: Max current
      description: Dynamically alter the max current while still allowing other claims to very the current via charge_current that can not exceede this value.
      required: false
      example: 32
      selector:
        number:
          min: 1
          max: 48
          unit_of_measurement: ampers
          mode: box
    energy_limit: 
      name: Energy limit
      description: Stop the charge after energy_limit Wh of energy have been transfered. (Not currently implemented)
      required: false
      selector:
        number:
          min: 1
          max: 2147483647
          unit_of_measurement: Wh
          mode: box
    time_limit:
      name: Time limit
      description: Stop the charge after the duration of the charging session has exceeded time_limit seconds. (Not currently implemented)
      required: false
      selector:
        number:
          min: 1
          max: 2147483647
          unit_of_measurement: seconds
          mode: box
    auto_release:
      name: Auto release
      description: If the manual override is auto-released when the vehicle is disconnected.
      required: false
      default: true
      example: true
      selector:
        boolean:

clear_override:
  name: Clear override
  description: Clears an override on a charger.
  target:
    device:
      integration: openevse  


set_limit:
  name: Set charge limit
  description: This will set the limit type, value and auto release.
  target:
    device:
      integration: openevse
  fields:
    type:
      name: Limit type
      description: 'Limit type: time (minutes), energy (watts/h), soc (%), range (km or miles).'
      required: true
      default: time
      example: time
      selector:
        select:
          options:
            - "time"
            - "energy"
            - "soc"
            - "range"
    value: 
      name: Limit value
      description: Stop the charge after the specified limit value.
      required: false
      selector:
        number:
          min: 1
          max: 2147483647
          mode: box
    auto_release:
      name: Auto release
      description: If the limit is auto-released when the vehicle is disconnected.
      required: false
      default: true
      example: true
      selector:
        boolean:

clear_limit:
  name: Clear limit
  description: Clears a limit on a charger.
  target:
    device:
      integration: openevse          

get_limit:
  name: Get limit
  description: Gets a limit on a charger.
  target:
    device:
      integration: openevse        

make_claim:
  name: Make Claim
  description: Make/Update a claim.
  target:
    device:
      integration: openevse
  fields:
    state:
      name: State
      description: Enable or disable charging.
      required: false
      default: disabled
      example: disabled
      selector:
        select:
          options:
            - "active"
            - "disabled"
    charge_current: 
      name: Charge current
      description: Specify the active charge current in Amps
      required: false
      example: 30
      selector:
        number:
          min: 1
          max: 48
          unit_of_measurement: ampers
          mode: box
    max_current:
      name: Max current
      description: Dynamically alter the max current while still allowing other claims to very the current via charge_current that can not exceede this value.
      required: false
      example: 32
      selector:
        number:
          min: 1
          max: 48
          unit_of_measurement: ampers
          mode: box
    auto_release:
      name: Auto release
      description: If the manual override is auto-released when the vehicle is disconnected.
      required: false
      default: true
      example: true
      selector:
        boolean:      
release_claim:
  name: Release claim
  description: Releases a claim on a charger.
  target:
    device:
      integration: openevse               
list_claims:
  name: List claims
  description: Lists claims on an EVSE.
  target:
    device:
      integration: openevse        
list_overrides:
  name: List overrides
  description: Lists overrides on an EVSE.
  target:
    device:
      integration: openevse    