blank_issues_enabled: false
contact_links:
  - name: Ask a question / Support Request
    url: https://github.com/firstof9/openevse/discussions
    about: Please ask questions and get support on GitHub Discussions.
